### ISSUE TITLE
calib3d(docs): misleading/ wrong documentation for RT

### ISSUE THREAD

**Issue by FischerGundlach** [opencv/opencv#16292]
* I ~do volunteer~ would like to work on this issue.
* I ran some tests with simulation data to check my assumptions, see below. 

##### Detailed description
Many functions within the calib3d module compute or rely on the extrinsics R and T in the camera model. The rigid transformation given by (R, T) describe the change of coordinates for a point `\mathbf{p}` in object coordinates to its representation in camera coordinates: `\mathbf{p}^{cam} = \mathbf{R} \mathbf{p}^{obj} + \mathbf{t}`.

Unfortunately, there are several problems in connection with this in the documentation. 

###### Wrong Documentation
* The documentation of `calibrateCamera` states "rotation vector together with (...) translation vector (...) brings the calibration pattern from the model coordinate space (...) to the *world coordinate space*". It should rather say *brings to camera coordinates*. 

* The documentation of `stereoCalibrate` states "(...) the position and orientation of the second camera relative to the first camera. This is what the described function does. It computes ( R, T ) (...) " However, (R, T) describe the change of coordinates from cam1 to cam2, and not the position of cam2. There is a duality, see below.

* The documentations of `projectPoints`, `recoverPose`, `decomposeEssentialMat`, and `decomposeHomographyMat` are rather unexplicit.

###### Unexplicit Documentation
* The documentation for `calibrateHandEye` is explicit about the meaning of (R, T) and its direction, e.g. `R_gripper2base`. The docs on the camera models are not so explicit. 
* The `T` vector is easy to inter. However, one needs to know, that `T` is given in the camera's coordinate system. 
* The documentation on `reprojectImage3D` and `triangulatePoints` does not state the coordinate system in which the points are returned. This seems to be an issue for [many](https://answers.opencv.org/question/118966/is-cvtriangulatepoints-returning-3d-points-in-world-coordinate-system/) people.

###### Duality
The problems with the documentation wouldn't be problems, if not for the duality of poses and change of coordinates. Whereas OpenCV uses (R, T) as a change of coordinates, i.e. it relates the same vector in two different coordinate systems, other frameworks like VTK and Blender use (R, T) as the camera's pose (orientation + position), i.e. it transforms a point to generate a new point, both in the same coordinate system `\mathbf{p}_{new}^{world} = \mathbf{R} \mathbf{p}_{old}^{world} + \mathbf{t}`. These two concepts are closely related, as one is the inverse to the other, see [this](http://www.boris-belousov.net/2016/05/31/change-of-basis/). 

##### Summary
The topic of change of coordinates in OpenCV is not hard to grasp but extremely error-prone. One needs to be careful to use points in their correct coordinate representation and not mix notations and concepts. Rigorous and explicit documentation will help people to speed up their development and also consolidate their understanding of the matter. 

I also believe that a section in the modules docs or a tutorial on working with a change of coordinates will be helpful. 

##### Naming of Camera Matrix
The module's detailed description and some functions' documentation denote the camera matrix with A, whereas others use K. We should pick one and change the other ones accordingly. Furthermore, some functions show the camera matrix's form while others don't. This should be unified. The same is true for the distortion coefficients. 

##### Code I Used for Testing
I set up (virtual) cameras and calibration patterns projected points and used `solvePnP`, `CalibrateCamera` and `StereoCalibrate` to solve for extrinsics. Eventually, I compared the found extrinsic parameters to the ground truth and print the norm of the max. deviation (over all elements in R, T). The results prints values in order `e-07`. 

See complete code [here](https://gist.github.com/FischerGundlach/b6b383e32e977ca0bc0de7121d316845). This code might also transform into a tutorial? 

##### Tasks
- [x] Fork + Clone, set up local build and testing pipeline 
- [ ] Find references on concepts change of coordinates/ transformation
- [x] List all occurrences in the current module documentation that need attention
- [x] Change Occurences in
   - [x] Into + Detailed Description
   - [x] `calibrateCamera`
   - [x] `stereoCalibrate`
   - [x] `stereoRectify`
   - [x] `projectPoints`
   - [x] `recoverPose`
   - [x] `decomposeEssentialMat`
   - [x] `decomposeHomographyMat` 
   - [x] `reprojectImage3D`
   - [x] `triangulatePoints`
- [x] Only correct spelling, grammar, line length etc. if I touched thed function's documentation anyway.
- [x] [Make it a good pull request](https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request)

**Comment by ljere** [comment]
I would suggest you use the book "Learning OpenCV" by Adrian Kaehler and Gary Bradski as a reference  to improve the documentation. In the book the meaning of R and T are explained in detail.

**Comment by FischerGundlach** [comment]
I am busy this week but will get back to it next weekend.
