### ISSUE TITLE
OpenCV4.2 android Sdk function bug in Mat src = new Mat(32, 32, CvType.CV_8UC1, Bytebuffer);

### ISSUE THREAD

**Issue by lesterlu** [opencv/opencv#16936]
##### System information (version)

- OpenCV =>4.2:
- Operating System / Platform => android
- Compiler =>no compile. use sdk direct

##### Detailed description

OpenCV4.2 android Sdk function bug in Mat src = new Mat(32, 32, CvType.CV_8UC1, Bytebuffer);
##### Steps to reproduce
Just use 
ByteBuffer buffer = ByteBuffer.allocate(1024);
buffer.put(colorValue);//this is array full of my color value in byte
Mat src = new Mat(32, 32, CvType.CV_8UC1, buffer);// assert fail 
then error happen. it says
CV_Assert(total() == 0 || data != NULL);
in this file 
OpenCV-android-sdk\sdk\native\jni\include\opencv2\core\mat.inl.hpp  line 548
But!!when use 
 Mat src = new Mat(32, 32, CvType.CV_8UC1);
src.put(0,0,colorValue);
it is OK!!! so this is a bug in data while mapping data from Java to C++.
Please fit it!

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
`ByteBuffer` wrapping into `Mat` is low level API.
It is here to support Camera2 API, not for User applications.
Several limitations must be applied, like using of **direct** `ByteBuffer`. See `.allocateDirect()` for example.

**Comment by lesterlu** [comment]
All right. so it's not a bug? i will close this issue now. Thanks for help.
