### ISSUE TITLE
How should I do to make pycharm auto-complete the cv2. function?

### ISSUE THREAD

**Issue by JimXu1989** [opencv/opencv#17072]
##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by dkurt** [comment]
Please take a look at issue template. This is a bug tracker and probably it will be more efficient to use StackOverflow or our forum: https://answers.opencv.org/

**Comment by alalek** [comment]
duplicate of #16758
