### ISSUE TITLE
Behaviour of uchar divide differs when working per pixel from working with Mat1b directly.

### ISSUE THREAD

**Issue by dsimonovic** [opencv/opencv#17099]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => OS X 10.15.3
- Compiler => Apple clang version 11.0.0

##### Detailed description

In Mat1b, behaviour of uchar divided by a number differs when:
1) working per pixel -> result is truncated
2) working with Mat1b directly -> result is rounded

##### Steps to reproduce

```.cpp
#include "opencv2/opencv.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main() {
    Mat1b m1(1,1), m2(1,1);
    m1<<3;
    m2<<3;

    m1/=4;
    m2[0][0]/=4;

    cout<<m1<<endl;
    cout<<m2<<endl;

    return 0;
}
```

Output:
```
[  1]
[  0]
```

Expected output:
```
[  0]
[  0]
```

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
Rounding and floating point computations are applied here due scalar is interpreted as `double` (and inverted `/4` => `* 0.25`).

See `cv::divide()`, `cv::convertTo(dst, depth, alpha, beta)`

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by dsimonovic** [comment]
The same issue applies for multiplication with double. Behaviour is not uniform:
```.cpp
m1<<3;m2<<3
m1*=0.25
m2[0][0]*=0.25;
```
If non-uniform behaviour is desired, please close this issue.

**Comment by alalek** [comment]
> m2[0][0]*=0.25;

C++ uses truncation.

OpenCV uses rounding to nearest even: https://en.wikipedia.org/wiki/Rounding#Round_half_to_even
