### ISSUE TITLE
Error in generating .pbtxt file from given .pb file/frozen graph file.

### ISSUE THREAD

**Issue by abhik-99** [opencv/opencv#17399]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => Linux 64 Bit
- Tensorflow Version => 2.0

##### Detailed description
I encounter this issue when I am trying to generate a .pbtxt file from frozen graph (.pb) file of a model using tf_text_graph_ssd.py found at [OpenCV/samples/dnn](https://github.com/opencv/opencv/tree/master/samples/dnn). The model I am trying to get the .pbtxt file from is [ssd_mobilenet_v1_coco](https://github.com/abhik-99/People-Counter-Tracker/tree/master/ssd_mobilenet_v1_coco). 
I'm using Intel OpenVINO and the OpenCV that ships with it. However, I get an error:
`Traceback (most recent call last):
  File "/home/workspace/opencv/samples/dnn/tf_text_graph_common.py", line 313, in writeTextGraph
    cv.dnn.writeTextGraph(modelPath, outputPath)
AttributeError: module 'cv2.dnn' has no attribute 'writeTextGraph'

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):

> 
>   File "/home/workspace/opencv/samples/dnn/tf_text_graph_common.py", line 313, in writeTextGraph
>     cv.dnn.writeTextGraph(modelPath, outputPath)
> AttributeError: module 'cv2.dnn' has no attribute 'writeTextGraph'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tf_text_graph_ssd.py", line 405, in <module>
>     createSSDGraph(args.input, args.config, args.output)
>   File "tf_text_graph_ssd.py", line 128, in createSSDGraph
>     writeTextGraph(modelPath, outputPath, outNames)
>   File "/home/workspace/opencv/samples/dnn/tf_text_graph_common.py", line 316, in writeTextGraph
>     from tensorflow.tools.graph_transforms import TransformGraph
> ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'`

##### Steps to reproduce

> python tf_text_graph_ssd.py --input /home/workspace/public/ssd_mobilenet_v1_coco/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.pb --config /home/workspace/public/ssd_mobilenet_v1_coco/ssd_mobilenet_v1_coco_2018_01_28/pipeline.config --output exported_pbtext/output.pbtxt

##### Issue submission checklist

 - [x] I report the issue, it's not a question - **Yes**
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution - **Yes**
   
 - [x] I updated to latest OpenCV version and the issue is still there
    - **I have to use the OpenCV shipped with Intel OpenVINO. It says version 3.3.1**
 - [x] There is reproducer code and related data files: videos, images, onnx, etc - **Yes. Please click on the link to my repo**

**Comment by dkurt** [comment]
> OpenCV => 3.3.1

Please use master branch

**Comment by abhik-99** [comment]
I cannot switch to standalone OpenCV. Intel OpenVINO is being used for inference and that ships with OpenCV as well which is the only option here.

**Comment by dkurt** [comment]
@abhik-99, I see but 3.3.1 is old release - you have to use corresponding python scripts from the same release or update OpenVINO.

Please use issues to report bugs properly for actual code base. Use a forum for questions.
