### ISSUE TITLE
CUDA: brush up detecting/supporting CUDA

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#17433]
##### System information (version)

- OpenCV => 3.4, master
- Operating System / Platform => Linux, Windows, Mac

##### Detailed description

First of all, I'm writing this issue on my personal interest.
Nothing related to my work or the company I belong

This is a proposal.
Looking at [OpenCVDetectCUDA.cmake](https://github.com/opencv/opencv/blob/a45928045a90493d45bd69244ea906d523900ba0/cmake/OpenCVDetectCUDA.cmake), there are couple things that could make things better

- [x] CUDA capability automatic detection (#17432)
- [ ] Drop support on old CC (already proposed in #16649)
 - Also [OpenCVMinDepVersions.cmake](https://github.com/opencv/opencv/blob/5ef548a985fc64dc89e8a6fdfa4e3889b1519780/cmake/OpenCVMinDepVersions.cmake) should be updated (may be 8.0?)
https://github.com/opencv/opencv/blob/5ef548a985fc64dc89e8a6fdfa4e3889b1519780/cmake/OpenCVMinDepVersions.cmake#L4
 - If dropping older than CC 5.0, then probably removing these lines are needed
https://github.com/opencv/opencv/blob/5ef548a985fc64dc89e8a6fdfa4e3889b1519780/cmake/OpenCVDetectCUDA.cmake#L133-L138
https://github.com/opencv/opencv/blob/5ef548a985fc64dc89e8a6fdfa4e3889b1519780/cmake/OpenCVDetectCUDA.cmake#L95
 - Remove Jetson TK1 support
https://github.com/opencv/opencv/blob/5ef548a985fc64dc89e8a6fdfa4e3889b1519780/cmake/OpenCVDetectCUDA.cmake#L99-L102
- [x] Add CC on `aarch64` (#17593)
 - [NVIDIA announced CUDA on `aarch64`](https://nvidianews.nvidia.com/news/nvidia-brings-cuda-to-arm-enabling-new-path-to-exascale-supercomputing), 

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by tomoaki0705** [comment]
I think I can close this issue.
Maybe we need a cleanup in the future again, but let close this issue for now.
