### ISSUE TITLE
Build Opencv 4.4.0 with Cuda support: make error: undefined reference to

### ISSUE THREAD

**Issue by maky-hnou** [opencv/opencv#18082]
##### System information (version)
- OpenCV == 4.4.0
- Operating System / Platform == Ubuntu 20.04
- Compiler == gcc-8  
- GPU: GTX1650  
- Cuda: 10.1, V10.1.243  
- CuDNN: 7.6.5  
- Compute capability: 7.5
- Cuda emplacement: `/usr/lib/cuda/` 
##### Detailed description
I wanted to build OpenCV from source with Cuda support.  For that:  
- I downloaded both opencv-4.4.0.zip and opencv_contrib-4.4.0.zip. 
- Unzipped both files and renamed them opencv and opencv_contrib, respectively.  
- created a folder named `build` in opencv and entered it then run the command:  
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=OFF \
-D OPENCV_ENABLE_NONFREE=ON \
-D WITH_CUDA=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D CUDA_ARCH_BIN=7.5 \
-D WITH_CUBLAS=1 \
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
-D HAVE_opencv_python3=ON \
-D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
-D CUDA_ARCH_PTX="" \
-D WITH_LIBV4L=ON \
-D WITH_V4L=ON \
-D WITH_GSTREAMER=ON \
-D WITH_QT=ON \
-D WITH_OPENGL=ON \
-D BUILD_opencv_python2=OFF \
-D CUDNN_INCLUDE_DIR=/usr/lib/cuda/include \
-D CUDNN_LIBRARY=/usr/lib/cuda/lib64/libcudnn_static.a \
-D CUDNN_VERSION=7.6.5 \
-D CMAKE_C_COMPILER=/usr/bin/gcc-8 \
../
```
Here is the output of the cmake command:  
[cmake_output.txt](https://github.com/opencv/opencv/files/5065409/cmake_output.txt)

I guess everything went right.  
- After that, I run `make -j12`, which got me some errors:  
```
[ 81%] Building CXX object modules/dnn_superres/CMakeFiles/opencv_perf_dnn_superres.dir/perf/perf_dnn_superres.cpp.o
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosInitializeCriticalSection'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosLeaveCriticalSection'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosProcessId'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosLoadLibrary'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosOnce'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosGetProcAddress'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosInit'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosFreeLibrary'
/usr/bin/ld: ../../lib/libopencv_dnn.so.4.4.0: undefined reference to `culibosEnterCriticalSection'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/dnn/CMakeFiles/opencv_perf_dnn.dir/build.make:190: bin/opencv_perf_dnn] Error 1
make[1]: *** [CMakeFiles/Makefile2:5831: modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
``` 
Here is the full output of the make command:  
 
[make_output.txt](https://github.com/opencv/opencv/files/5065438/make_output.txt)  
- After that, the make command stopped at:  
```
[ 86%] Built target opencv_test_gapi
make: *** [Makefile:163: all] Error 2
```
**Did anyone face the same problem?**  
**How to solve this problem?**

##### Issue submission checklist

 - [x] I report the issue, and I ask how to solve it
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by maky-hnou** [comment]
I found a similar issue in this [link](https://forums.developer.nvidia.com/t/cudnn-static-linking-error/60707)  
The user is talking about adding this code:  
```
set(CUDNN_ROOT_DIR "" CACHE PATH "Folder contains NVIDIA cuDNN")

SET(CUDNN_LIBNAME "cudnn_static")
SET(CULIBOS_LIBNAME "culibos")

find_path(CUDNN_INCLUDE_DIR cudnn.h
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES cuda/include include)

find_library(CUDNN_LIBRARY ${CUDNN_LIBNAME}
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64)
    
find_library(CULIBOS_LIBRARY ${CULIBOS_LIBNAME}
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64)

set(CUDNN_LIBRARIES ${CUDNN_LIBRARY} ${CULIBOS_LIBRARY})
``` 
to `opencv/cmake/FindCUDNN.cmake` file.  
I'll try it and report.

**Comment by alalek** [comment]
> libcudnn_static.a

Why do you use static library?

> CULIBOS_LIBRARY

Not necessary in case of shared libraries.

> CUDNN_LIBRARY=

It is a list. No problem to add several items.
Add all necessary dependencies as static library required.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by maky-hnou** [comment]
@alalek  I added `CUDNN_INCLUDE_DIR` and `CUDNN_LIBRARY` because my installation path of Cuda and CuDNN are in different path than the usual: When I installed them using `sudo apt install nvidia-cuda-toolkit` they were installed in `/usr/lib/` instead of `/usr/local/`.  
So without adding those flags to the `cmake` command, I get a warning that Cuda and CuDNN were not detected.

**Comment by maky-hnou** [comment]
The problem was solved by adding the following code to `opencv/cmake/FindCUDNN.cmake`:  
```
set(CUDNN_ROOT_DIR "" CACHE PATH "Folder contains NVIDIA cuDNN")

SET(CUDNN_LIBNAME "cudnn_static")
SET(CULIBOS_LIBNAME "culibos")

find_path(CUDNN_INCLUDE_DIR cudnn.h
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES cuda/include include)

find_library(CUDNN_LIBRARY ${CUDNN_LIBNAME}
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64)
    
find_library(CULIBOS_LIBRARY ${CULIBOS_LIBNAME}
    HINTS ${CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64)

set(CUDNN_LIBRARIES ${CUDNN_LIBRARY} ${CULIBOS_LIBRARY})
```

I added it to the end of the file as it is, without making any changes.  
After that I run `make -j12` (12 is based on the number of cores of the CPU)  and all the rest of the build command without any problems.  
I tested Opencv 4.4.0 with YOLOv4 and it works fine.

**Comment by MoscowskyAnton** [comment]
@maky-hnou hello, I tried your solution, but my configure ends with errors, did you apply this changes after or before configuring opencv with cmake?

**Comment by maky-hnou** [comment]
Hello @MoscowskyAnton, I applied them before running `cmake`.  
Maybe you have cuda and cudnn in different paths? Or maybe the cuad_architecture_bin is different than mine.  
For the record, I followed this tutorial: https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/  But I made some changes to make it work for me.

**Comment by MoscowskyAnton** [comment]
I've tested.
That @maky-hnou's solution works for OpenCV 4.4.0, CUDA 11.0 and cuDNN 8.0.5 and nVidia GeForce GTX 1050 ti. Tested with [dnn adapted tensorflow nets](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API).

First you need to configure OpenCV
Than fix FindCUDNN.cmake
And after that make it

**Comment by maky-hnou** [comment]
I am glad it worked for you.
