### ISSUE TITLE
Unable to reproduce warpAffine results

### ISSUE THREAD

**Issue by NoVarlok** [opencv/opencv#18475]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu lts 20.04
- Compiler => g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0

##### Detailed description

I tried to reproduce the warpAffine result for bilinear interpolation with a constant borderMode in my own function, using formulas from the wiki. However, my result is slightly different. Is it possible that opencv uses some special or modified formulas for bilinear interpolation?
Also reproduced Nearest Neighbor interpolation, but it's ok (Error = 0.05%).
I compared my result with Halcon and it's almost the same.

##### Steps to reproduce

Source code in the attachment

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc
   

##### Sources
[source.zip](https://github.com/opencv/opencv/files/5307327/source.zip)
   -->
