### ISSUE TITLE
Depth Image from Compressed Colorized Image

### ISSUE THREAD

**Issue by NRutigliano** [opencv/opencv#18945]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 18.04.5 LTS

##### Detailed description

Hello,
In the interests of my thesis project, I need to build a code that can de-compress a depth image and convert it into a Point Cloud. I am working with ROS.
I apparently have no issue with the de-compression nor in the generation of the point cloud.
To perform this procedure I am following the whitepaper at [this link](https://dev.intelrealsense.com/docs/depth-image-compression-by-colorization-for-intel-realsense-depth-cameras#section-3-2-depth-image-recovery-from-colorized-depth-images-in-c).
In synthesis, the camera applies a filter to a depth grayscale image that colorizes it.
Then, the image is compressed and published as a ROS Compressed Image topic.
Then, my ROS package converts the compressed image into a standard image.
Then, I have to transform the colorized image into a depth grayscale image, from which I then extract the PointCloud.

My issue is in this last step. As shown in the figure below, the code should produce a replica of the original depth image, but it doesn't.
![9429424-fig-1](https://user-images.githubusercontent.com/56929171/100439034-45930e80-30a3-11eb-908b-51e63174bbfc.png)

If anyone encountered this issue in the past or if you just have an idea on how to solve it, it would mean a lot. I'm stuck on this problem for quite along. Thanks

##### Here's the code

Python node to perform decompression:
```
#!/usr/bin/env python2
#from _future_ import print_function
import sys, time
import cv2
import numpy as np
import roslib
import rospy
import message_filters
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image, CompressedImage, CameraInfo
from std_msgs.msg import String, Header
from std_msgs.msg import Float32MultiArray
from transforms3d.euler import euler2mat, mat2euler
from transforms3d.axangles import axangle2mat

class Decompressor:


	# Try to tune the queue_size value. Maybe increase it up to the frequency.	

	def __init__(self):
        	'''Initialize ros publisher, ros subscriber'''
        	# topic where we publish
        	self.image_pub  = rospy.Publisher("/output/image", Image,queue_size=1)

		self.bridge = CvBridge()
		
        	# subscribed Topic
        	self.subscriber = rospy.Subscriber("/camera/depth/image_rect_raw/compressed",
 CompressedImage,self.callback,queue_size=1)
		
	def callback(self,ros_data):

		image_np = self.bridge.compressed_imgmsg_to_cv2(ros_data,"bgr8")

        	out_img = self.bridge.cv2_to_imgmsg(image_np,"bgr8")
		out_img.header = ros_data.header
		#self.image_pub.publish(self.bridge.cv2_to_imgmsg(image_np,"rgb8"))
		self.image_pub.publish(out_img)		
		
class passthrough_class:
	def __init__(self):
		self.info_pub  = rospy.Publisher("/output/camera_info", CameraInfo,queue_size=1)
		self.info_sub = rospy.Subscriber("/camera/depth/camera_info", CameraInfo,self.callback,queue_size=1)
	def callback(self,data):
		self.info_pub.publish(data)

def main(args):
	'''Initializes and cleanup ros node'''
    	rospy.init_node('Decompressor', anonymous=True)
	ic = Decompressor()
	pt = passthrough_class()

    	try:
        	rospy.spin()
    	except KeyboardInterrupt:
        	print "Shutting down ROS Image converter module"
#    	cv2.destroyAllWindows()

if __name__ == '__main__':
	main(sys.argv)
```
C++ node for image conversion and point cloud generation

```
#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/image_encodings.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/CameraInfo.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/point_cloud2_iterator.h>
#include <std_msgs/String.h>
#include <pcl_ros/point_cloud.h>
#include <pcl_ros/publisher.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/filters/voxel_grid.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/core.hpp>
#include <vector>
#include <Eigen/Eigen>
#include <iostream>
#include <thread>
#include <chrono>
#include <fstream>
#include <string>
#include <atomic>
#include <opencv2/opencv.hpp>
#include <boost/thread.hpp>

static const std::string OPENCV_WINDOW = "Depth image *10";	// SHOW IMAGE

class ImageConverter
{
  ros::NodeHandle nh_;
  image_transport::ImageTransport it_;
  image_transport::Subscriber image_sub_;
  image_transport::Publisher image_pub_;
  ros::Publisher cloud_pub = nh_.advertise<sensor_msgs::PointCloud2> ("/converter/depth/points", 1);
public:
  ImageConverter()
    : it_(nh_)
  {
   // Subscribe colorized Image and publish depth Image

   image_sub_ = it_.subscribe("/output/image", 1, &ImageConverter::imageCb, this);
   image_pub_ = it_.advertise("/converter/depth/image", 1);
   cv::namedWindow(OPENCV_WINDOW);	// SHOW IMAGE
  }

  ~ImageConverter()
  {
    cv::destroyWindow(OPENCV_WINDOW);	// SHOW IMAGE
  }

  unsigned short RGBtoD(unsigned char r, unsigned char g, unsigned char b)
  {
   // Conversion from RGB color to quantized depth values. Configured for Hue colorization method.

	if(b+g+r < 255) //255 128
	{
		return 0;
	}
	else if (r >= g && r >= b)
	{
		if (g >= b)
		{	
			return g - b;
		}
		else
		{
			return (g - b) + 1529; //1529 1535
		}
	}
	else if (g >= r && g >= b)
	{
		return b - r + 510; //510 512
	}
	else if (b >= g && b >= r)
  	{
		return r - g + 1020; //1020 1024
	}
  }


  void ColorizedDepthToDepth(cv::Mat& color_mat, cv::Mat& depth_mat)
  {
   // Convert Colorized Image to quantized Depth Image
   // Image size
   int _width =848 ;
   int _height = 480;
   bool is_disparity = false;
   // Min and Max depth range for the camera. Value is in meters
   float min_depth = 0.29; // to avoid depth inversion, it’s offset from 0.3 to 0.29.
   float max_depth = 6.0; // 64.0
   float min_disparity = 1.0f / max_depth;
   float max_disparity = 1.0f / min_depth;
   // This is a scale value. It is technically acquired from the camera laser. Here it's imported from realsense-viewer
   float depth_units = 0.0010;

   unsigned short hue_value = 0; // from 0 to 255 * 6-1 = 0-1529 by Hue colorization

   auto in = reinterpret_cast<const unsigned char*>(color_mat.data);	// Input Image matrix
   auto out = reinterpret_cast<unsigned short*>(depth_mat.data);	// Output Image matrix

   for (int i = 0; i < _height; i++)
   {
    for (int j = 0; j < _width; j++)
    {
     unsigned char R = *in++;
     unsigned char G = *in++;
     unsigned char B = *in++;
     unsigned short hue_value = RGBtoD(R, G, B);

     if(hue_value > 0)
     {
      if(!is_disparity)
      {
       unsigned short z_value = static_cast<unsigned short>((min_depth + (max_depth - min_depth) * hue_value / 1529.0f) / depth_units); //1529
       *out++ = z_value;
      }
      else
      {
       float disp_value = min_disparity + (max_disparity - min_disparity) * hue_value / 1529.0;//1529
       *out++ = static_cast<unsigned short>((1.0f / disp_value)/depth_units + 0.5);
      }
     }
     else
     {
      *out++ = 0;
     }
    }
   }
  }
  void ComputePointCloud(cv::Mat& depth_mat, std::vector<float>& point_cloud)
  {
   float depth_units = 0.0010;
   point_cloud.clear();
   for (int y = 0; y < 480; y++)
   {
    for (int x = 0; x < 848; x++)
    {
     auto depth_value = depth_mat.at<unsigned short>(y, x);
     if (depth_value > 0)
     {
      point_cloud.push_back(depth_value * (x - 419.7328186035156) / 424.0969543457031 * depth_units * 1000.0f );	//* 1000.0f
      point_cloud.push_back(depth_value * (y - 237.46710205078125) / 424.0969543457031 * depth_units * 1000.0f );//* 1000.0f
      point_cloud.push_back((float)depth_value * depth_units * 1000.0f );//* 1000.0f
     }
    }
   }
  }


  void imageCb(const sensor_msgs::ImageConstPtr& msg)
  {
    cv_bridge::CvImagePtr cv_ptr;	// Subscribed Image Declaration.
    try
    {

      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::RGB8);	// Subscribed Image assigned.
      auto depth_mat = cv::Mat(cv::Size(848,480), CV_16U).setTo(0);		// Depth Image declaration.
      ColorizedDepthToDepth(cv_ptr->image,depth_mat);
       // Update GUI Window
      cv::imshow(OPENCV_WINDOW, depth_mat*10);	// SHOW IMAGE
      cv::waitKey(3);	// SHOW IMAGE
      

	// PointCloud2 Message generation

	std::vector<float> point_cloud;
	
	ComputePointCloud(depth_mat,point_cloud);

	std::vector<float> points;
	float depth_scale = 0.0010;
	Eigen::Matrix3f K;
	Eigen::Matrix3f invK;
	K << 424.0969543457031, 0.0, 419.7328186035156, 0.0, 424.0969543457031, 237.46710205078125, 0.0, 0.0, 1.0;
	invK = K.inverse();	

	for (int i=0;i<depth_mat.rows;i++)
	{
	 const unsigned short* row_ptr = depth_mat.ptr<unsigned short>(i);
	 for (int j=0;j<depth_mat.cols;j++)
	 {
	  unsigned short id = row_ptr[j];
	  if(id!=0)
	  {
	   float d=depth_scale*id;
           Eigen::Vector3f image_point(j*d,i*d,d);
           Eigen::Vector3f camera_point=invK*image_point; //*0.50f
	   points.push_back(camera_point.x());
	   points.push_back(camera_point.y());
	   points.push_back(camera_point.z());
	  }
	 }
	}

	int n_points = points.size();
	sensor_msgs::PointCloud2 cloud_msg;
	sensor_msgs::PointCloud2Modifier modifier(cloud_msg);
	modifier.setPointCloud2Fields(3, "x", 1, sensor_msgs::PointField::UINT16, "y", 1, sensor_msgs::PointField::UINT16,"z", 1, sensor_msgs::PointField::UINT16); //FLOAT32
	modifier.setPointCloud2FieldsByString(1, "xyz");
	modifier.resize(n_points);
	sensor_msgs::PointCloud2Iterator<float> iter_x(cloud_msg, "x");
	sensor_msgs::PointCloud2Iterator<float> iter_y(cloud_msg, "y");
	sensor_msgs::PointCloud2Iterator<float> iter_z(cloud_msg, "z");
	cloud_msg.height = 1;
	cloud_msg.width = n_points;
	cloud_msg.header.frame_id = msg->header.frame_id;
	cloud_msg.header.seq = msg->header.seq;
	cloud_msg.header.stamp = msg->header.stamp;
    	
	for(size_t i=0; i<n_points/3; ++i, ++iter_x, ++iter_y, ++iter_z)
	{
	 *iter_x = points[3*i+0];
	 *iter_y = points[3*i+1];
	 *iter_z = points[3*i+2];
	 //std::cerr << *iter_x << " " << *iter_y << " " << *iter_z << std::endl;	// It display x,y,z points' coordinates on terminal.
	}

	cloud_pub.publish(cloud_msg);
	//std::cerr << ".";
    }    
	    catch (cv_bridge::Exception& e)
    {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
    }
  }
};

int main(int argc, char** argv)
{
  ros::init(argc, argv, "image_converter");
  ImageConverter ic;
  ros::spin();
  return 0;
}
```

##### Issue submission checklist
 - [x] I checked the problem with the documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
 - [ ] I updated to the latest OpenCV version and the issue is still there
    - [x] There are reproducer code and related data files: videos, images, onnx, etc

**Comment by NRutigliano** [comment]
> ##### System information (version)
> * OpenCV => 3.2.0
> * Operating System / Platform => Ubuntu 18.04.5 LTS
> 
> ##### Detailed description
> Hello,
> In the interests of my thesis project, I need to build a code that can de-compress a depth image and convert it into a Point Cloud. I am working with ROS.
> I apparently have no issue with the de-compression nor in the generation of the point cloud.
> To perform this procedure I am following the whitepaper at [this link](https://dev.intelrealsense.com/docs/depth-image-compression-by-colorization-for-intel-realsense-depth-cameras#section-3-2-depth-image-recovery-from-colorized-depth-images-in-c).
> In synthesis, the camera applies a filter to a depth grayscale image that colorizes it.
> Then, the image is compressed and published as a ROS Compressed Image topic.
> Then, my ROS package converts the compressed image into a standard image.
> Then, I have to transform the colorized image into a depth grayscale image, from which I then extract the PointCloud.
> 
> My issue is in this last step. As shown in the figure below, the code should produce a replica of the original depth image, but it doesn't.
> ![9429424-fig-1](https://user-images.githubusercontent.com/56929171/100439034-45930e80-30a3-11eb-908b-51e63174bbfc.png)
> 
> If anyone encountered this issue in the past or if you just have an idea on how to solve it, it would mean a lot. I'm stuck on this problem for quite along. Thanks
> 
> ##### Here's the code
> Python node to perform decompression:
> 
> ```
> #!/usr/bin/env python2
> #from _future_ import print_function
> import sys, time
> import cv2
> import numpy as np
> import roslib
> import rospy
> import message_filters
> from cv_bridge import CvBridge, CvBridgeError
> from sensor_msgs.msg import Image, CompressedImage, CameraInfo
> from std_msgs.msg import String, Header
> from std_msgs.msg import Float32MultiArray
> from transforms3d.euler import euler2mat, mat2euler
> from transforms3d.axangles import axangle2mat
> 
> class Decompressor:
> 
> 
> 	# Try to tune the queue_size value. Maybe increase it up to the frequency.	
> 
> 	def __init__(self):
>         	'''Initialize ros publisher, ros subscriber'''
>         	# topic where we publish
>         	self.image_pub  = rospy.Publisher("/output/image", Image,queue_size=1)
> 
> 		self.bridge = CvBridge()
> 		
>         	# subscribed Topic
>         	self.subscriber = rospy.Subscriber("/camera/depth/image_rect_raw/compressed",
>  CompressedImage,self.callback,queue_size=1)
> 		
> 	def callback(self,ros_data):
> 
> 		image_np = self.bridge.compressed_imgmsg_to_cv2(ros_data,"bgr8")
> 
>         	out_img = self.bridge.cv2_to_imgmsg(image_np,"bgr8")
> 		out_img.header = ros_data.header
> 		#self.image_pub.publish(self.bridge.cv2_to_imgmsg(image_np,"rgb8"))
> 		self.image_pub.publish(out_img)		
> 		
> class passthrough_class:
> 	def __init__(self):
> 		self.info_pub  = rospy.Publisher("/output/camera_info", CameraInfo,queue_size=1)
> 		self.info_sub = rospy.Subscriber("/camera/depth/camera_info", CameraInfo,self.callback,queue_size=1)
> 	def callback(self,data):
> 		self.info_pub.publish(data)
> 
> def main(args):
> 	'''Initializes and cleanup ros node'''
>     	rospy.init_node('Decompressor', anonymous=True)
> 	ic = Decompressor()
> 	pt = passthrough_class()
> 
>     	try:
>         	rospy.spin()
>     	except KeyboardInterrupt:
>         	print "Shutting down ROS Image converter module"
> #    	cv2.destroyAllWindows()
> 
> if __name__ == '__main__':
> 	main(sys.argv)
> ```
> 
> C++ node for image conversion and point cloud generation
> 
> ```
> #include <ros/ros.h>
> #include <image_transport/image_transport.h>
> #include <cv_bridge/cv_bridge.h>
> #include <sensor_msgs/image_encodings.h>
> #include <sensor_msgs/Image.h>
> #include <sensor_msgs/CameraInfo.h>
> #include <sensor_msgs/PointCloud2.h>
> #include <sensor_msgs/point_cloud2_iterator.h>
> #include <std_msgs/String.h>
> #include <pcl_ros/point_cloud.h>
> #include <pcl_ros/publisher.h>
> #include <pcl_conversions/pcl_conversions.h>
> #include <pcl/point_cloud.h>
> #include <pcl/point_types.h>
> #include <pcl/filters/voxel_grid.h>
> #include <opencv2/imgproc/imgproc.hpp>
> #include <opencv2/highgui/highgui.hpp>
> #include <opencv2/imgproc.hpp>
> #include <opencv2/highgui.hpp>
> #include <opencv2/imgcodecs/imgcodecs.hpp>
> #include <opencv2/imgcodecs.hpp>
> #include <opencv2/core/core.hpp>
> #include <opencv2/core.hpp>
> #include <vector>
> #include <Eigen/Eigen>
> #include <iostream>
> #include <thread>
> #include <chrono>
> #include <fstream>
> #include <string>
> #include <atomic>
> #include <opencv2/opencv.hpp>
> #include <boost/thread.hpp>
> 
> static const std::string OPENCV_WINDOW = "Depth image *10";	// SHOW IMAGE
> 
> class ImageConverter
> {
>   ros::NodeHandle nh_;
>   image_transport::ImageTransport it_;
>   image_transport::Subscriber image_sub_;
>   image_transport::Publisher image_pub_;
>   ros::Publisher cloud_pub = nh_.advertise<sensor_msgs::PointCloud2> ("/converter/depth/points", 1);
> public:
>   ImageConverter()
>     : it_(nh_)
>   {
>    // Subscribe colorized Image and publish depth Image
> 
>    image_sub_ = it_.subscribe("/output/image", 1, &ImageConverter::imageCb, this);
>    image_pub_ = it_.advertise("/converter/depth/image", 1);
>    cv::namedWindow(OPENCV_WINDOW);	// SHOW IMAGE
>   }
> 
>   ~ImageConverter()
>   {
>     cv::destroyWindow(OPENCV_WINDOW);	// SHOW IMAGE
>   }
> 
>   unsigned short RGBtoD(unsigned char r, unsigned char g, unsigned char b)
>   {
>    // Conversion from RGB color to quantized depth values. Configured for Hue colorization method.
> 
> 	if(b+g+r < 255) //255 128
> 	{
> 		return 0;
> 	}
> 	else if (r >= g && r >= b)
> 	{
> 		if (g >= b)
> 		{	
> 			return g - b;
> 		}
> 		else
> 		{
> 			return (g - b) + 1529; //1529 1535
> 		}
> 	}
> 	else if (g >= r && g >= b)
> 	{
> 		return b - r + 510; //510 512
> 	}
> 	else if (b >= g && b >= r)
>   	{
> 		return r - g + 1020; //1020 1024
> 	}
>   }
> 
> 
>   void ColorizedDepthToDepth(cv::Mat& color_mat, cv::Mat& depth_mat)
>   {
>    // Convert Colorized Image to quantized Depth Image
>    // Image size
>    int _width =848 ;
>    int _height = 480;
>    bool is_disparity = false;
>    // Min and Max depth range for the camera. Value is in meters
>    float min_depth = 0.29; // to avoid depth inversion, it’s offset from 0.3 to 0.29.
>    float max_depth = 6.0; // 64.0
>    float min_disparity = 1.0f / max_depth;
>    float max_disparity = 1.0f / min_depth;
>    // This is a scale value. It is technically acquired from the camera laser. Here it's imported from realsense-viewer
>    float depth_units = 0.0010;
> 
>    unsigned short hue_value = 0; // from 0 to 255 * 6-1 = 0-1529 by Hue colorization
> 
>    auto in = reinterpret_cast<const unsigned char*>(color_mat.data);	// Input Image matrix
>    auto out = reinterpret_cast<unsigned short*>(depth_mat.data);	// Output Image matrix
> 
>    for (int i = 0; i < _height; i++)
>    {
>     for (int j = 0; j < _width; j++)
>     {
>      unsigned char R = *in++;
>      unsigned char G = *in++;
>      unsigned char B = *in++;
>      unsigned short hue_value = RGBtoD(R, G, B);
> 
>      if(hue_value > 0)
>      {
>       if(!is_disparity)
>       {
>        unsigned short z_value = static_cast<unsigned short>((min_depth + (max_depth - min_depth) * hue_value / 1529.0f) / depth_units); //1529
>        *out++ = z_value;
>       }
>       else
>       {
>        float disp_value = min_disparity + (max_disparity - min_disparity) * hue_value / 1529.0;//1529
>        *out++ = static_cast<unsigned short>((1.0f / disp_value)/depth_units + 0.5);
>       }
>      }
>      else
>      {
>       *out++ = 0;
>      }
>     }
>    }
>   }
>   void ComputePointCloud(cv::Mat& depth_mat, std::vector<float>& point_cloud)
>   {
>    float depth_units = 0.0010;
>    point_cloud.clear();
>    for (int y = 0; y < 480; y++)
>    {
>     for (int x = 0; x < 848; x++)
>     {
>      auto depth_value = depth_mat.at<unsigned short>(y, x);
>      if (depth_value > 0)
>      {
>       point_cloud.push_back(depth_value * (x - 419.7328186035156) / 424.0969543457031 * depth_units * 1000.0f );	//* 1000.0f
>       point_cloud.push_back(depth_value * (y - 237.46710205078125) / 424.0969543457031 * depth_units * 1000.0f );//* 1000.0f
>       point_cloud.push_back((float)depth_value * depth_units * 1000.0f );//* 1000.0f
>      }
>     }
>    }
>   }
> 
> 
>   void imageCb(const sensor_msgs::ImageConstPtr& msg)
>   {
>     cv_bridge::CvImagePtr cv_ptr;	// Subscribed Image Declaration.
>     try
>     {
> 
>       cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::RGB8);	// Subscribed Image assigned.
>       auto depth_mat = cv::Mat(cv::Size(848,480), CV_16U).setTo(0);		// Depth Image declaration.
>       ColorizedDepthToDepth(cv_ptr->image,depth_mat);
>        // Update GUI Window
>       cv::imshow(OPENCV_WINDOW, depth_mat*10);	// SHOW IMAGE
>       cv::waitKey(3);	// SHOW IMAGE
>       
> 
> 	// PointCloud2 Message generation
> 
> 	std::vector<float> point_cloud;
> 	
> 	ComputePointCloud(depth_mat,point_cloud);
> 
> 	std::vector<float> points;
> 	float depth_scale = 0.0010;
> 	Eigen::Matrix3f K;
> 	Eigen::Matrix3f invK;
> 	K << 424.0969543457031, 0.0, 419.7328186035156, 0.0, 424.0969543457031, 237.46710205078125, 0.0, 0.0, 1.0;
> 	invK = K.inverse();	
> 
> 	for (int i=0;i<depth_mat.rows;i++)
> 	{
> 	 const unsigned short* row_ptr = depth_mat.ptr<unsigned short>(i);
> 	 for (int j=0;j<depth_mat.cols;j++)
> 	 {
> 	  unsigned short id = row_ptr[j];
> 	  if(id!=0)
> 	  {
> 	   float d=depth_scale*id;
>            Eigen::Vector3f image_point(j*d,i*d,d);
>            Eigen::Vector3f camera_point=invK*image_point; //*0.50f
> 	   points.push_back(camera_point.x());
> 	   points.push_back(camera_point.y());
> 	   points.push_back(camera_point.z());
> 	  }
> 	 }
> 	}
> 
> 	int n_points = points.size();
> 	sensor_msgs::PointCloud2 cloud_msg;
> 	sensor_msgs::PointCloud2Modifier modifier(cloud_msg);
> 	modifier.setPointCloud2Fields(3, "x", 1, sensor_msgs::PointField::UINT16, "y", 1, sensor_msgs::PointField::UINT16,"z", 1, sensor_msgs::PointField::UINT16); //FLOAT32
> 	modifier.setPointCloud2FieldsByString(1, "xyz");
> 	modifier.resize(n_points);
> 	sensor_msgs::PointCloud2Iterator<float> iter_x(cloud_msg, "x");
> 	sensor_msgs::PointCloud2Iterator<float> iter_y(cloud_msg, "y");
> 	sensor_msgs::PointCloud2Iterator<float> iter_z(cloud_msg, "z");
> 	cloud_msg.height = 1;
> 	cloud_msg.width = n_points;
> 	cloud_msg.header.frame_id = msg->header.frame_id;
> 	cloud_msg.header.seq = msg->header.seq;
> 	cloud_msg.header.stamp = msg->header.stamp;
>     	
> 	for(size_t i=0; i<n_points/3; ++i, ++iter_x, ++iter_y, ++iter_z)
> 	{
> 	 *iter_x = points[3*i+0];
> 	 *iter_y = points[3*i+1];
> 	 *iter_z = points[3*i+2];
> 	 //std::cerr << *iter_x << " " << *iter_y << " " << *iter_z << std::endl;	// It display x,y,z points' coordinates on terminal.
> 	}
> 
> 	cloud_pub.publish(cloud_msg);
> 	//std::cerr << ".";
>     }    
> 	    catch (cv_bridge::Exception& e)
>     {
>       ROS_ERROR("cv_bridge exception: %s", e.what());
>       return;
>     }
>   }
> };
> 
> int main(int argc, char** argv)
> {
>   ros::init(argc, argv, "image_converter");
>   ImageConverter ic;
>   ros::spin();
>   return 0;
> }
> ```
> 
> ##### Issue submission checklist
> * [x]  I checked the problem with the documentation, FAQ, open issues,
>   answers.opencv.org, Stack Overflow, etc and have not found a solution
> * [ ]  I updated to the latest OpenCV version and the issue is still there
>   
>   * [x]  There are reproducer code and related data files: videos, images, onnx, etc

UPDATE:
By disabling the camera histogram equalization filter, the reconstructed image has gotten way better, but I'm quite sure the image overall quality can still improve. I will update when I will get satisfying results

**Comment by dkurt** [comment]
Please do not use GitHub issues for usage questions because we need this to track bugs and feature requests.
