### ISSUE TITLE
module 'cv2.cv2' has no attribute

### ISSUE THREAD

**Issue by farazmoradi** [opencv/opencv#19591]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by vipin1326** [comment]
Try to install opencv-contrib and try again. It will work.
pip install opencv-contrib-python
