### ISSUE TITLE
emcc error code 1

### ISSUE THREAD

**Issue by ChristianBarette** [opencv/opencv#19730]
##### System information (version)
- OpenCV => 4.5.0
- Operating System / Platform => Windows 10 / 64 Bit
- Compiler => Visual Studio 2021 1.54
- Cmake 3.20.0-rc2
- Emscripten 1.38.31

##### Detailed description

In a Windows CMD terminal, when I type the command :  
build_js.py --opencv_dir C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources --emscripten_dir C:\Users\Chris\Desktop\Webdev\emsdk\emsdk-master\emscripten\1.38.31 C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\build

the following error occurs : 
CMake Error at C:/Users/Chris/Desktop/Webdev/emsdk/emsdk-master/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake:113 (message):
Failed to fetch compiler version information with command
"'C:/Users/Chris/Desktop/Webdev/emsdk/emsdk-master/emscripten/1.38.31/emcc.bat'
-v"! Process returned with error code 1.

see attached file :
[emcc_error.txt](https://github.com/opencv/opencv/files/6142911/emcc_error.txt)
[emcc_error.txt](https://github.com/opencv/opencv/files/6142914/emcc_error.txt)

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
relates #19700

Do not open duplicate issues. This would not help.
Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

---

> "'C:/Users/Chris/Desktop/Webdev/emsdk/emsdk-master/emscripten/1.38.31/emcc.bat'
-v"! Process returned with error code 1.

Try to run mentioned command in your build environment.

If this doesn't work, then your emscripten installation is incorrect.
You should refer to Emscripten documentation for proper installation.
Please note OpenCV JS guidelines are wrote and verified for Linux only.

**Comment by ChristianBarette** [comment]
OK I move to Users OpenCV Q/A forum: https://forum.opencv.org/
