### ISSUE TITLE
Error using fisheye callibration in python

### ISSUE THREAD

**Issue by Praveenstein** [opencv/opencv#20603]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

```
OpenCV Error: Assertion failed (objectPoints.type() == CV_32FC3 || objectPoints.type() == CV_64FC3) in calibrate, file /Users/jesper/opencv3/opencv/modules/calib3d/src/fisheye.cpp, line 695
Traceback (most recent call last):
  File "extract.py", line 71, in <module>
    print cv2.fisheye.calibrate(obj_points, img_points, (w, h), None, None)
cv2.error: /Users/jesper/opencv3/opencv/modules/calib3d/src/fisheye.cpp:695: error: (-215) objectPoints.type() == CV_32FC3 || objectPoints.type() == CV_64FC3 in function calibrate
```
##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc
