### ISSUE TITLE
build error! multiple definition of `cv::cuda::GpuMat::defaultAllocator()'

### ISSUE THREAD

**Issue by fightmoney** [opencv/opencv#20678]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform =>  ubuntu 18.04
- CUDA 10.2

##### Detailed description
When I build opencv with CUDA ,there is something wrong.

```
[ 29%] Linking CXX shared library ../../lib/libopencv_core.so
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::defaultAllocator()':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat16defaultAllocatorEv+0x0): multiple definition of `cv::cuda::GpuMat::defaultAllocator()'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat16defaultAllocatorEv+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::setDefaultAllocator(cv::cuda::GpuMat::Allocator*)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat19setDefaultAllocatorEPNS1_9AllocatorE+0x0): multiple definition of `cv::cuda::GpuMat::setDefaultAllocator(cv::cuda::GpuMat::Allocator*)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat19setDefaultAllocatorEPNS1_9AllocatorE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::release()':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat7releaseEv+0x0): multiple definition of `cv::cuda::GpuMat::release()'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat7releaseEv+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::create(int, int, int)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat6createEiii+0x0): multiple definition of `cv::cuda::GpuMat::create(int, int, int)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat6createEiii+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::upload(cv::_InputArray const&)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat6uploadERKNS_11_InputArrayE+0x0): multiple definition of `cv::cuda::GpuMat::upload(cv::_InputArray const&)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat6uploadERKNS_11_InputArrayE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::upload(cv::_InputArray const&, cv::cuda::Stream&)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat6uploadERKNS_11_InputArrayERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::upload(cv::_InputArray const&, cv::cuda::Stream&)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat6uploadERKNS_11_InputArrayERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::download(cv::_OutputArray const&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat8downloadERKNS_12_OutputArrayE+0x0): multiple definition of `cv::cuda::GpuMat::download(cv::_OutputArray const&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat8downloadERKNS_12_OutputArrayE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::download(cv::_OutputArray const&, cv::cuda::Stream&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat8downloadERKNS_12_OutputArrayERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::download(cv::_OutputArray const&, cv::cuda::Stream&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat8downloadERKNS_12_OutputArrayERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayE+0x0): multiple definition of `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&, cv::cuda::Stream&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&, cv::cuda::Stream&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::cuda::Stream&)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat5setToENS_7Scalar_IdEERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::cuda::Stream&)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat5setToENS_7Scalar_IdEERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&, cv::_InputArray const&, cv::cuda::Stream&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayERKNS_11_InputArrayERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::copyTo(cv::_OutputArray const&, cv::_InputArray const&, cv::cuda::Stream&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat6copyToERKNS_12_OutputArrayERKNS_11_InputArrayERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::_InputArray const&, cv::cuda::Stream&)':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZN2cv4cuda6GpuMat5setToENS_7Scalar_IdEERKNS_11_InputArrayERNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::_InputArray const&, cv::cuda::Stream&)'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZN2cv4cuda6GpuMat5setToENS_7Scalar_IdEERKNS_11_InputArrayERNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::convertTo(cv::_OutputArray const&, int, cv::cuda::Stream&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat9convertToERKNS_12_OutputArrayEiRNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::convertTo(cv::_OutputArray const&, int, cv::cuda::Stream&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat9convertToERKNS_12_OutputArrayEiRNS0_6StreamE+0x0): first defined here
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o: In function `cv::cuda::GpuMat::convertTo(cv::_OutputArray const&, int, double, double, cv::cuda::Stream&) const':
tmpxft_00003947_00000000-5_gpu_mat.compute_61.cudafe1.cpp:(.text._ZNK2cv4cuda6GpuMat9convertToERKNS_12_OutputArrayEiddRNS0_6StreamE+0x0): multiple definition of `cv::cuda::GpuMat::convertTo(cv::_OutputArray const&, int, double, double, cv::cuda::Stream&) const'
CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o:cuda_gpu_mat.cpp:(.text._ZNK2cv4cuda6GpuMat9convertToERKNS_12_OutputArrayEiddRNS0_6StreamE+0x0): first defined here
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_core.dir/build.make:2141: recipe for target 'lib/libopencv_core.so.3.3.0' failed
make[2]: *** [lib/libopencv_core.so.3.3.0] Error 1
CMakeFiles/Makefile2:2458: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [1] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by fightmoney** [comment]
this is my cmake choose
```
General configuration for OpenCV 3.3.0 =====================================
--   Version control:               unknown
-- 
--   Extra modules:
--     Location (extra):            /home/zsj/opencv-3.3.0/opencv_contrib-3.3.0/modules
--     Version control (extra):     unknown
-- 
--   Platform:
--     Timestamp:                   2021-09-09T06:02:52Z
--     Host:                        Linux 5.4.0-77-generic x86_64
--     CMake:                       3.10.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
--       SSE4_1 (2 files):          + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (7 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++11:                       YES
--     C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         YES
--     Extra dependencies:          /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libcblas.so /usr/lib/x86_64-linux-gnu/libatlas.so gtk-3 gdk-3 pangocairo-1.0 pango-1.0 atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 gthread-2.0 /usr/lib/x86_64-linux-gnu/libwebp.so /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so dc1394 avcodec avformat avutil swscale avresample gphoto2 gphoto2_port vtkRenderingOpenGL vtkImagingHybrid vtkIOImage vtkCommonDataModel vtkCommonMath vtkCommonCore vtksys vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkDICOMParser vtkIOCore vtkmetaio /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libtiff.so vtkImagingCore vtkRenderingCore vtkCommonColor vtkFiltersExtraction vtkFiltersCore vtkFiltersGeneral vtkCommonComputationalGeometry vtkFiltersStatistics vtkImagingFourier vtkalglib vtkFiltersGeometry vtkFiltersSources vtkInteractionStyle vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOGeometry vtkFiltersTexture vtkRenderingFreeType /usr/lib/x86_64-linux-gnu/libfreetype.so vtkftgl vtkIOExport vtkRenderingAnnotation vtkImagingColor vtkRenderingContext2D vtkRenderingGL2PS vtkRenderingContextOpenGL /usr/lib/x86_64-linux-gnu/libgl2ps.so vtkRenderingLabel /usr/lib/x86_64-linux-gnu/libprotobuf.so freetype harfbuzz /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libm.so /usr/lib/x86_64-linux-gnu/libglog.so gflags_shared dl m pthread rt cudart nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/local/cuda-10.2/lib64 -L/usr/lib/x86_64-linux-gnu
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 cudev core cudaarithm flann hdf imgproc ml objdetect phase_unwrapping plot reg surface_matching video viz xphoto bgsegm cudabgsegm cudafilters cudaimgproc cudawarping dnn dnn_modern face freetype fuzzy img_hash imgcodecs photo shape videoio xobjdetect highgui ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo datasets rgbd stereo structured_light superres tracking videostab xfeatures2d ximgproc aruco optflow sfm stitching python2 python3
--     Disabled:                    cudacodec world contrib_world
--     Disabled by dependency:      -
--     Unavailable:                 java cnn_3dobj cvv matlab
-- 
--   GUI: 
--     QT:                          NO
--     GTK+ 3.x:                    YES (ver 3.22.30)
--     GThread :                    YES (ver 2.56.4)
--     GtkGlExt:                    NO
--     OpenGL support:              NO
--     VTK support:                 YES (ver 6.3.0)
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
--     WEBP:                        /usr/lib/x86_64-linux-gnu/libwebp.so (ver encoder: 0x020e)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 - 4.0.9)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2.2.0)
--     GDAL:                        NO
--     GDCM:                        NO
-- 
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  YES (ver 2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 57.107.100)
--       avformat:                  YES (ver 57.83.100)
--       avutil:                    YES (ver 55.78.100)
--       swscale:                   YES (ver 4.8.100)
--       avresample:                YES (ver 3.7.0)
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     Aravis SDK:                  NO
--     UniCap:                      NO
--     UniCap ucil:                 NO
--     V4L/V4L2:                    NO/YES
--     XIMEA:                       NO
--     Xine:                        NO
--     Intel Media SDK:             NO
--     gPhoto2:                     YES
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Use Intel IPP:               2017.0.2 [2017.0.2]
--                at:               /home/zsj/opencv-3.3.0/build/3rdparty/ippicv/ippicv_lnx
--     Use Intel IPP IW:            prebuilt binaries (2017.0.2)
--     Use Intel IPP Async:         NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Lapack:                  YES (/usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libcblas.so /usr/lib/x86_64-linux-gnu/libatlas.so)
--     Use Eigen:                   YES (ver 3.3.4)
--     Use Cuda:                    YES (ver 10.2)
--     Use OpenCL:                  YES
--     Use OpenVX:                  NO
--     Use custom HAL:              NO
-- 
--   NVIDIA CUDA
--     Use CUFFT:                   YES
--     Use CUBLAS:                  YES
--     USE NVCUVID:                 YES
--     NVIDIA GPU arch:             30 35 37 50 52 60 61
--     NVIDIA PTX archs:
--     Use fast math:               YES
-- 
--   OpenCL:                        <Dynamic loading of OpenCL library>
--     Include path:                /home/zsj/opencv-3.3.0/3rdparty/include/opencl/1.2
--     Use AMDFFT:                  NO
--     Use AMDBLAS:                 NO
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.17)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.17)
--     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.13.3)
--     packages path:               lib/python2.7/dist-packages
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.6.9)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.9)
--     numpy:                       /usr/local/lib/python3.6/dist-packages/numpy/core/include (ver 1.19.5)
--     packages path:               lib/python3.6/dist-packages
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:
--     ant:                         NO
--     JNI:                         /usr/lib/jvm/java-8-openjdk-amd64/include /usr/lib/jvm/java-8-openjdk-amd64/include/linux /usr/lib/jvm/java-8-openjdk-amd64/include
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:
--     mex:                         /usr/local/MATLAB/R2021a/bin/mex
--     Compiler/generator:          Not working (bindings will not be generated)
-- 
--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           YES
--     C/C++ Examples:              NO
-- 
--   Install path:                  /usr/local
-- 
--   cvconfig.h is in:              /home/zsj/opencv-3.3.0/build
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zsj/opencv-3.3.0/build

```

**Comment by alalek** [comment]
Check dependencies releases dates and think how they can be supported by OpenCV before their official releases.

---

> OpenCV => 3.3.0

Outdated releases are not going to be fixed.

> I updated to latest OpenCV version and the issue is still there

You should do this first.
