### ISSUE TITLE
imdecode fails to handle IMREAD_REDUCED_COLOR_X flag on Linux

### ISSUE THREAD

**Issue by gwy15** [opencv/opencv#20931]
##### System information (version)
- OpenCV => 4.2 (4.2.0+dfsg-5 from apt)
- Operating System / Platform => Linux (ubuntu)
- Compiler => clang

##### Detailed description

When using `imdecode` with `IMREAD_REDUCED_COLOR_X` flags on Linux, opencv ignores the `IMREAD_REDUCED_COLOR_X` flag and returns the image in the original size. A 1/8 sized image is expected. This behaves as expected on Windows but not on Linux.

##### Steps to reproduce

1. Read a jpg image to memory and store it in `Vector<uint8_t>`.
2. Call `cv::imdecode(data, cv::IMREAD_REDUCED_COLOR_8)`
3. The output is in raw size, not in a reduced size.

You can see my code here with the example image: https://github.com/gwy15/opencv_testcase
```c++
#include <opencv2/imgcodecs.hpp>
#include <iostream>
#include <fstream>
#include <vector>
#include <cstdint>

int main() {
    std::cout << "expected size: [1440 x 2048]" << std::endl;

    cv::Mat img = cv::imread(
        "./e09ca4a57584181ce573e45079b524ff3859b9fb.jpg",
        cv::IMREAD_REDUCED_COLOR_8
    );
    std::cout << "imread size: " << img.size() << std::endl;

    std::ifstream instream("./e09ca4a57584181ce573e45079b524ff3859b9fb.jpg", std::ios::in | std::ios::binary);
    std::vector<uint8_t> data = std::vector<uint8_t>(std::istreambuf_iterator<char>(instream), std::istreambuf_iterator<char>());
    cv::Mat img2 = cv::imdecode(
        data,
        cv::IMREAD_REDUCED_COLOR_8
    );
    std::cout << "imdecode size: " << img2.size() << std::endl;

    return 0;
}
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found solution*.
 - [x] I updated to latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

*: I checked this issue https://github.com/opencv/opencv/issues/16203 and this PR https://github.com/opencv/opencv/pull/16309, which should fix 3.4 I guess? But in my version of opencv it still is buggy.
