### ISSUE TITLE
How to confirm the version of the OpenCV 3rdParty libs

### ISSUE THREAD

**Issue by wangch1009** [opencv/opencv#21509]
##### System information (version)
- OpenCV = 4.5.2
- Operating System / Platform => Linux
- Compiler => gcc version 4.8.5

##### Detailed description
I need to obtain each software version in the 3rdparty directory in the source code of OpenCV 4.5.2 to analyze whether OpenCV 4.5.2 has dependency vulnerabilities.But the third-party software version is not found in the code repository or in the document.For example, the versions of open-source software such as carotene, cpufeatures, ippicv, and ittnotify cannot be confirmed.
![image](https://user-images.githubusercontent.com/98326538/150894923-7303e9a0-ddc4-4b8e-be37-77a0ff583cf1.png)

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc
