### ISSUE TITLE
Opencv error with GPU backend

### ISSUE THREAD

**Issue by DanyResasco** [opencv/opencv#21619]
##### System information (version)

- OpenCV => 4.5.5-dev
- Operating System / Platform => Ubuntu 20
- Compiler => GCC

##### Detailed description

I cannot run anymore my cv2.dnn on GPU. 
I tried to run the code in CPU and its workings. I also tested with the older version of OpenCV and is working. I think the new commit merged in February changed the dnn output is an np.array[] and is not compatible with 4.5.5 release version. Could you please give an example of how to use the new output?

##### Steps to reproduce
    ```.python
     //with CUDA enabled
    net = cv2.dnn.readNetFromONNX(model_yolo_v5))
    net.setInput(_image)
    results = net.forward()
    ```
##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by fengyuentau** [comment]
Feel free to re-open with model provided for us to reproduce.
