### ISSUE TITLE
to extract frame type (I, P, B) info for better post-process without ffmpeg/ffprobe

### ISSUE THREAD

**Issue by NewUserHa** [opencv/opencv#21859]
##### System information (version)
- OpenCV => opencv-python 4.5.5
- Operating System / Platform => win10
- Compiler => pre-compiled

##### Detailed description
Currently, it always needs FFmpeg/FFprobe to extract frame type info before any future processing, but calling a new process is slow and complex for other codes.
I,P,B frame type info could be useful to do some scene-change detection.

But OpenCV currently misses the function to get that info, but it should be there when OpenCV reads the video files.
Could OpenCV enhance this feature?

Thanks
##### Steps to reproduce
N/A

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc
