### ISSUE TITLE
cv2.imread() fails when filenames have multiple dots (.)

### ISSUE THREAD

**Issue by FacePlanter2** [opencv/opencv#22003]
##### System information (version)

- OpenCV => 4.5.5.64
- Operating System / Platform => Windows
- Compiler => PyCharm Community Edition 2020.1.1

##### Detailed description

When the `cv2.imread()` method encounters a filename with multiple dots (.), a `NoneType` is returned. I think this might be because the file extension is assumed to be everything after the first dot, and not the last, but it could be something completely different.

Example: 

##### Steps to reproduce

 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by s39674** [comment]
Hi @calvinindustriesrepresentative i think you meant the first one failed and the second one loaded successfully, is that right?
anyway, I am having a hard time reproducing the same error:
```python
img = cv.imread('test project – main.py 18_05_2022 15_44_50.png') # works fine, also with full path
img = cv.imread('..........png') # also works fine
```
Have you tried putting the image in the same directory as your code, and omitting the full path?
could you try renaming the image to: `main.py.png` and post your results?
