### ISSUE TITLE
Big OpenCV Cleanup

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#25007]
### Describe the feature and motivation

We need to clean [OpenCV 5.0](https://github.com/orgs/opencv/projects/1) codebase, especially the main repository, in order to create room for new functionality and reduce maintenance effort.

This is the master ticket that refers to several child topics:

- [ ] (???) [Use standard C++ types in API](https://github.com/opencv/opencv/issues/24994)
- [x] (WIP, multiple PRs) [Clean Core module](https://github.com/opencv/opencv/issues/25002)
- [ ] (WIP, multiple PRs) [Clean Imgproc module](https://github.com/opencv/opencv/issues/25001)
- [x] (WIP, #25292) [Clean Features2D, rename it to Features](https://github.com/opencv/opencv/issues/24999)
- [x] (WIP, #25708) [Replace FLANN with new smaller and better implementation](https://github.com/opencv/opencv/issues/24998)
- [x] [Clean Objdetect module](https://github.com/opencv/opencv/issues/25004)
- [x] [Move ML module to opencv_contrib](https://github.com/opencv/opencv/issues/24997)
- [x] [Remove OpenVX](https://github.com/opencv/opencv/issues/24995)
- [x] (???) [Move IPP to opencv/3rdparty](https://github.com/opencv/opencv/issues/24996)
- [x] [Move G-API to opencv_contrib or to the separate opencv/G-API repository](https://github.com/opencv/opencv/issues/25000)
- [x] [Clean Samples](https://github.com/opencv/opencv/issues/25006)

**Comment by s-trinh** [comment]
Maybe pin also this ticket to avoid it being submerged by issues? And keep it visible?

Just saw that there is also https://github.com/opencv/opencv/projects?query=is%3Aopen but I am not used to it.

**Comment by vpisarev** [comment]
We are almost there. Let's target the remaining things in 5.1.
